### ISSUE TITLE
Ignore cargo registry from docker image

### ISSUE THREAD

**Issue by nim65s** [taiki-e/cargo-llvm-cov#104]
Hi,

When using this project inside the official [rust docker image](https://hub.docker.com/_/rust),  the coverage report include stuff from `/usr/local/cargo/registry/src/`.

I'm not sure how to read the exclude regex in
https://github.com/taiki-e/cargo-llvm-cov/blob/36866e5bd9e6e2f493b9bf8b7ad12e01a13b2217/src/main.rs#L541
so I don't know if it's just me doing something wrong or not.

Is there a way to exclude everything from this path ?

**Comment by taiki-e** [comment]
Fixed in v0.1.12. (#105)

**Comment by nim65s** [comment]
Perfect, thanks !
