### ISSUE TITLE
Usage in CI

### ISSUE THREAD

**Issue by taiki-e** [taiki-e/cargo-llvm-cov#12]
[codecov claims to support many formats](https://docs.codecov.io/docs/supported-report-formats), but it actually happens "There was an error processing coverage reports" errors on the server. It is necessary to understand which formats are actually supported and which ones are preferred to use.

I'm not sure about other code-coverage services as I have never used them.

**Comment by jhpratt** [comment]
Check out the time-rs/time repo. I _just_ added codecov using json successfully. lcov also worked.

**Comment by jhpratt** [comment]
Actually I stand corrected. JSON **does not** work. lcov does. https://app.codecov.io/gh/time-rs/time

**Comment by taiki-e** [comment]
Thanks @jhpratt. I also checked it in my test repository, it seems to work only with lcov. (Uploading of json and text reports succeeded, but an error happened in the server.)

**Comment by jhpratt** [comment]
No problem. It looks like codecov only cares about line coverage as well, rather than the more detailed report lcov provides. But I'm pretty sure that's on codecov's end.

**Comment by taiki-e** [comment]
> It looks like codecov only cares about line coverage as well, rather than the more detailed report lcov provides. But I'm pretty sure that's on codecov's end.

Hmm. It seems codecov supports branch coverage, so that might be a rustc's problem (#8, https://github.com/rust-lang/rust/issues/79649).

https://docs.codecov.io/docs/about-code-coverage

> partial indicates that the source code was not fully executed by the test suite; there are remaining branches that were not executed.

llvm-cov (that used by cargo-llvm-cov internally) also supports the export of branch coverage.

https://llvm.org/docs/CommandGuide/llvm-cov.html#llvm-cov-export

> When exporting an lcov trace file, the line-based coverage, branch coverage, and summaries will be exported.

**Comment by taiki-e** [comment]
> > It looks like codecov only cares about line coverage as well, rather than the more detailed report lcov provides. But I'm pretty sure that's on codecov's end.

We can probably support region coverage on codecov by converting llvm-cov's json coverage format to [codecov's json coverage format](https://docs.codecov.io/docs/codecov-custom-coverage-format).
