### ISSUE TITLE
Generating coverage report fails on Windows with too many objects

### ISSUE THREAD

**Issue by aganders3** [taiki-e/cargo-llvm-cov#124]
See this failed CI output from a coverage run: https://github.com/PyO3/pyo3/runs/4793968532?check_suite_focus=true

It seems this is a symptom of collecting coverage on a large number of output objects, and gives the error `(never executed): The filename or extension is too long. (os error 206)`. I don't actually think it's the filename or extension, but rather the total length of the command. In this case I believe it's something like 34,565 characters long (!) and the limit in Windows is apparently [32,768](https://stackoverflow.com/a/28452546/333308).

I am happy to work on a fix/workaround if somebody knows one, but I also unfortunately don't have direct access to a Windows machine at the moment.

**Comment by aganders3** [comment]
Hm, I tried to run this way and it seems like the comma-separated version of the `-object` arg may no longer be supported. For now I will try to find another workaround.

**Comment by taiki-e** [comment]
If llvm-cov accepts relative paths, we may be able to mitigate this problem by using `.strip_prefix(env::corrent_dir())` to paths to objects. like:

https://github.com/taiki-e/cargo-llvm-cov/blob/681f574529fce5917da4cdd9a5f5397860945753/src/cli.rs#L631-L632

**Comment by aganders3** [comment]
Thanks - good idea but I will have to test as I don't fully understand the `llvm-cov` docs on this:

> **`-compilation-dir=`**`<dir>`
> Directory used as a base for relative coverage mapping paths. Only applicable when binaries have been compiled with one of `-fcoverage-prefix-map` `-fcoverage-compilation-dir`, or `-ffile-compilation-dir`.
