### ISSUE TITLE
Got deprecated “-Z instrument-coverage” warning with nightly-2022-02-05 toolchain

### ISSUE THREAD

**Issue by EFanZh** [taiki-e/cargo-llvm-cov#129]
Now that <https://github.com/rust-lang/rust/pull/90132> is merged, using `-Z instrument-coverage` triggers `` `-Z instrument-coverage` is deprecated; use `-C instrument-coverage` `` warning now.

**Comment by taiki-e** [comment]
Published 0.2.0 which includes a fix for this.
