### ISSUE TITLE
Exclude build.rs from coverage reports

### ISSUE THREAD

**Issue by stouset** [taiki-e/cargo-llvm-cov#159]
Parts of a project that are loaded from `build.rs` have duplicated coverage reports, both under the standard package name and under the `build_script_build::` module prefix.

**Comment by taiki-e** [comment]
Thanks for the report! Could you provide the repro?

**Comment by stouset** [comment]
I am neck-deep in some stuff at the moment, but it's [this repo](https://github.com/stouset/stockfish-rs/). If you build it with `llvm-cov` you'll notice that many of the items are duplicated as part of `build_script_build` (e.g., `build.rs`).

Admittedly I'm doing some funky stuff in my build script. But also I wouldn't expect `llvm-cov` to instrument the invocation of the build script at all.

**Comment by taiki-e** [comment]
Thanks. I thought `--ignore-filename-regex=build.rs` would fix this, but it just hides the `build.rs` from the report.

I'm ok with excluding build scripts by default.
Filed #163.
