### ISSUE TITLE
cargo llvm-cov run changes `pwd`

### ISSUE THREAD

**Issue by Licenser** [taiki-e/cargo-llvm-cov#160]
When calling `cargo llvm-cov run` from a sub directory of the current workspace, `pwd` is changed from this directory to the workspace root before the runnable command is executed.

This makes it extremely hard to use `llvm-cov run` for testing when tests are structured into multiple folders.

**Comment by taiki-e** [comment]
Thanks. I think this was originally intended to make `--remap-path-prefix` or something work, but we don't use it anymore and I don't think the current dir change is needed any longer.

Filed #161 to fix.

**Comment by Licenser** [comment]
Oh wow, thank you so much for the quick help! You're amazing :D

**Comment by taiki-e** [comment]
Published 0.4.0 which includes the fix for this issue.
