### ISSUE TITLE
Save coverage even if tests fail

### ISSUE THREAD

**Issue by clarfonthey** [taiki-e/cargo-llvm-cov#169]
It would be nice to have the option to be able to still generate coverage even if tests fail, since it can still be useful even if the code needs to be modified for them to pass. Right now, running `cargo llvm-cov --html --open` will not generate the coverage and not open it if the tests fail.

**Comment by taiki-e** [comment]
This should already be available by using two commands, but I'm fine to add a specific command for it.

```
cargo llvm-cov --no-report --no-fast-fail || true
cargo llvm-cov --no-run --open
```

**Comment by taiki-e** [comment]
If we add an option for this (probably `--ignore-run-fail`?):

- Only run failures should be ignored. i.e., a build failure should fail as usual.
  - This is what commands I mentioned in the above comment do not handle well.
  - To implement this, first run `cargo test` with `--no-run` flag, then run regular `cargo test`, ignoring only the latter error. ([related code](https://github.com/taiki-e/cargo-llvm-cov/blob/8d63c9fd6c926a6ff0aa0b9768801c879321299a/src/main.rs#L303-L321))
- If this option is specified, the `--no-fast-failure` flag must be passed to cargo. (Without it, the test will be finished on failure.)
  - To avoid confusion, it is preferable to reject cases where both are used at the same time by using clap's conflicts option.
