### ISSUE TITLE
Clone is required in a bound by Copy, however Clone is marked as uncovered

### ISSUE THREAD

**Issue by DustinEwan** [taiki-e/cargo-llvm-cov#193]
As per the title, if you `#[derive(Copy)]` you must also `#[derive(Clone)]`.

However `Clone` will be marked as uncovered in the `#[derive(Clone, Copy)]` statement.

![image](https://user-images.githubusercontent.com/1225064/179424490-8dbcf8a3-12fa-4357-925d-4d80bc75354b.png)

**Comment by taiki-e** [comment]
This is the upstream issue: see https://github.com/rust-lang/rust/issues/84605#issuecomment-984287186 and subsequent 3 comments.

**Comment by taiki-e** [comment]
This will be fixed in https://github.com/rust-lang/rust/pull/120185.
