### ISSUE TITLE
Duplicate #[derive(...)] when it is placed on line 1 in --html option

### ISSUE THREAD

**Issue by TimePrinciple** [taiki-e/cargo-llvm-cov#195]
When `#[derive(...)]` is placed on line 1 of a file and then run `cargo llvm-cov --html`, the resulting Coverage report has two same and adjacent `#[derive(...)]` like this
![image](https://user-images.githubusercontent.com/52569592/179927669-4eb05619-6726-4d07-95b5-f43c8ba8182e.png)
After moving the first line to the second, it works normally again:
![image](https://user-images.githubusercontent.com/52569592/179927945-eeb22b14-4db4-46ec-bf99-54a2111612b4.png)

**Comment by taiki-e** [comment]
I believe this is a rustc (or llvm) bug.

**Comment by taiki-e** [comment]
@TimePrinciple Would you mind submitting an issue at https://github.com/rust-lang/rust?

**Comment by taiki-e** [comment]
(upstream issue: https://github.com/rust-lang/rust/issues/110749)

**Comment by taiki-e** [comment]
This should be fixed in https://github.com/rust-lang/rust/pull/97368.
