### ISSUE TITLE
Recompiles workspace crates every time

### ISSUE THREAD

**Issue by Eugeny** [taiki-e/cargo-llvm-cov#198]
Currently, running `cargo llvm-cov run` recompiles the workspace crates every time, making merging multiple runs with `--no-report` and `--no-run --html` unfeasible.

**Comment by taiki-e** [comment]
Could you provide an example to reproduce this?

Also, old results will be removed unless you pass `--no-report` to `cargo llvm-cov run`.

```
cargo llvm-cov run --no-report -- a
cargo llvm-cov run --no-report -- b
cargo llvm-cov --no-run --html
```

**Comment by Eugeny** [comment]
I've got [the repro](https://github.com/Eugeny/cargo-llvm-cov-repro) ready and then tried putting `--no-report` _after_ `run`, and it worked! Shame on me.

Might still be unexpected behaviour however, that:

* `--no-report` before `run` is silently ignored and 
* `--no-report` affects whether a rebuild happens

**Comment by taiki-e** [comment]
> * `--no-report` before `run` is silently ignored and

This is https://github.com/taiki-e/cargo-llvm-cov/issues/151, and will be fixed by https://github.com/taiki-e/cargo-llvm-cov/pull/197

> * `--no-report` affects whether a rebuild happens

[readme example](https://github.com/taiki-e/cargo-llvm-cov#merge-coverages-generated-under-different-test-conditions) describes `cargo llvm-cov clean` as a command to remove artifacts.

**Comment by Eugeny** [comment]
> This is https://github.com/taiki-e/cargo-llvm-cov/issues/151, and will be fixed by https://github.com/taiki-e/cargo-llvm-cov/pull/197

:+1:

> [readme example](https://github.com/taiki-e/cargo-llvm-cov#merge-coverages-generated-under-different-test-conditions) describes cargo llvm-cov clean as a command to remove artifacts.

Sorry if I wasn't clear - I've already figured out how to do / not do a rebuild, but it's still unexpected for a new user that adding `--no-report` will also change the build behaviour (it will force a rebuild every time).

**Comment by taiki-e** [comment]
> I've already figured out how to do / not do a rebuild, but it's still unexpected for a new user that adding --no-report will also change the build behaviour (and not just whether a report is generated)

Indeed. Adding a document to mention it seems like a good idea.

**Comment by fenollp** [comment]
I see that the workspace's bin crates are recompiled everytime as well. I can reproduce with the [provided repro repo](https://github.com/Eugeny/cargo-llvm-cov-repro).
My usage:
```shell
while :; do cargo llvm-cov --all-targets --all-features --locked --frozen; done

# Note: plain cargo test call does not recompile things:
while :; do cargo test --all-targets --all-features --locked --frozen; done
```
Please advise.

**Comment by Eugeny** [comment]
@fenollp adding `--no-report` should help. In my cases, I've ended up running it once and then running the compiled binary multiple times directly during my integration tests.

**Comment by taiki-e** [comment]
Added --no-clean flag as a workaround for this. See #214 for more.
