### ISSUE TITLE
Support region coverage on codecov

### ISSUE THREAD

**Issue by taiki-e** [taiki-e/cargo-llvm-cov#20]
readme says:

> Currently, only line coverage is available on Codecov. This is because `-Z instrument-coverage` does not support branch coverage and Codecov does not support region coverage.

However, we can probably support region coverage on codecov by converting llvm-cov's json coverage format to [codecov's json coverage format](https://docs.codecov.io/docs/codecov-custom-coverage-format).

related:
- https://llvm.org/docs/CoverageMappingFormat.html

**Comment by taiki-e** [comment]
Sorry, but I can't understand the question. (See [this LLVM patch](https://reviews.llvm.org/D84467) for what branch coverage means in the LLVM source-based code coverage and for example report it generates.)

**Comment by flying-sheep** [comment]
Never mind the definitions: What I mean is that `llvm-cov` seems (to my knowledge) to be the only tool that is able to visualize which exact parts of the source code have been executed and which haven’t.

Oher tools will show e.g. the following as “covered” or “partially covered”:

![](https://user-images.githubusercontent.com/291575/206483176-8d51afbe-4581-4076-a0eb-a8145a799d2f.png)

**Comment by andrewgazelka** [comment]
@taiki-e I am potentially interested on taking a stab at this. Do you already have a Rust deserialized version of `CoverageMappingFormat`?

**Comment by taiki-e** [comment]
> Do you already have a Rust deserialized version of `CoverageMappingFormat`?

`LlvmCovJsonExport` is the data structure for that.

https://github.com/taiki-e/cargo-llvm-cov/blob/ad889ca4b1f832f9c2570009eebf44b0fa48c4e8/src/json.rs#L9

**Comment by andrewgazelka** [comment]
> This is because -Z instrument-coverage does not support branch coverage

@taiki-e so https://github.com/taiki-e/cargo-llvm-cov/blob/e035f1d47f26ea4a66bfb4c5bc89e621903ab2a4/src/json.rs#L190 will always be `None`?

**Comment by taiki-e** [comment]
> will always be `None`?

IIRC, it will be empty list (`Some(vec![])`)

**Comment by andrewgazelka** [comment]
So we would want to check a separate arg here, right? Something like `--codecov-json`?

https://github.com/taiki-e/cargo-llvm-cov/blob/4c7c4963ad6ec8ba13152659ca079ac79576ec24/tests/auxiliary/mod.rs#L86-L102

**Comment by andrewgazelka** [comment]
@taiki-e here is a draft PR. I still need to test and add unit tests. Is there anything you would change?

https://github.com/taiki-e/cargo-llvm-cov/pull/249
