### ISSUE TITLE
Cannot merge multiple runs, coverage overwritten

### ISSUE THREAD

**Issue by Eugeny** [taiki-e/cargo-llvm-cov#201]
Since `LLVM_PROFILE_FILE` is always the same and only depends on the binary signatures, multiple `cargo llvm-cov run` calls will overwrite each other's coverage.

Adding a flag that adds `%p` to `LLVM_PROFILE_FILE` is the easiest workaround probably.

**Comment by taiki-e** [comment]
Thanks! Added `%p` to `LLVM_PROFILE_FILE` in 0.4.13.
