### ISSUE TITLE
New default profraw file name in Rust 1.65

### ISSUE THREAD

**Issue by wesleywiser** [taiki-e/cargo-llvm-cov#204]
Hi @taiki-e!

I just wanted to give you a heads up that we are changing the default profraw file name in Rust 1.65 (https://github.com/rust-lang/rust/pull/100384). Looking over your crate, I don't believe this will affect you since you explicitly set `LLVM_PROFILE_FILE` but wanted to let you know anyway.

**Comment by taiki-e** [comment]
Thanks for the heads up!

As you mentioned, we set LLVM_PROFILE_FILE so it would not be affected.

https://github.com/taiki-e/cargo-llvm-cov/blob/f7870c5df548613f62de4aa472db552a669ed09b/src/main.rs#L230

However, https://github.com/rust-lang/rust/pull/100384 may help avoid the problem of profiles being ignored when LLVM_PROFILE_FILE is removed.

https://github.com/taiki-e/cargo-llvm-cov/blob/863a8a053c3ded2863b032fbe024c7a74bfa68d0/tests/fixtures/crates/bin_crate/tests/test.rs#L17-L24

**Comment by taiki-e** [comment]
Closing -- We are not affected by this issue.
