### ISSUE TITLE
[question/feature request] Is there an api show every test case run time ?

### ISSUE THREAD

**Issue by jiangying000** [taiki-e/cargo-llvm-cov#210]
output like:

`test::some_test 100ms`

**Comment by taiki-e** [comment]
There are two ways:

- Use rustc's unstable features: `cargo llvm-cov -- -Z unstable-options --report-time` (see https://github.com/crossbeam-rs/crossbeam/pull/855#discussion_r908540125 for screenshot)
- Use `cargo llvm-cov nextest`: see [nextest](https://github.com/nextest-rs/nextest) for more
