### ISSUE TITLE
[maybe bug] `export CARGO_LLVM_COV_TARGET_DIR="./target"` make coverage dropped to near zero

### ISSUE THREAD

**Issue by jiangying000** [taiki-e/cargo-llvm-cov#211]
https://github.com/starcoinorg/starcoin/pull/3701/commits/b8896a889322f8ea971560d047b9f2f9d4b37e3a

I added `export CARGO_LLVM_COV_TARGET_DIR="./target` , want to fix binary path for a test case, but resulting coverage dropped from  55% to 0.5%

the pr is https://github.com/starcoinorg/starcoin/pull/3701, coverage report change https://github.com/starcoinorg/starcoin/runs/8093661553

Is this a bug or I did something wrong ? 

thank you

**Comment by taiki-e** [comment]
I guess you probably need to use the absolute path.

**Comment by jiangying000** [comment]
> I guess you probably need to use the absolute path.

OK, I'd try out

**Comment by jiangying000** [comment]
> I guess you probably need to use the absolute path.

absolute path works, thank you

**Comment by taiki-e** [comment]
FYI, #218 added warning for CARGO_LLVM_COV_TARGET_DIR with relative path.


```console
$ CARGO_LLVM_COV_TARGET_DIR="./target" cargo llvm-cov 
warning: CARGO_LLVM_COV_TARGET_DIR with relative path may not work properly; consider using absolute path
```

**Comment by jiangying000** [comment]
> 

that's nice

**Comment by taiki-e** [comment]
CARGO_LLVM_COV_TARGET_DIR with relative path has been supported in [0.5.0](https://github.com/taiki-e/cargo-llvm-cov/releases/tag/v0.5.0).
