### ISSUE TITLE
--jobs seems not used when running `cargo llvm-cov nextest --jobs 1`

### ISSUE THREAD

**Issue by jiangying000** [taiki-e/cargo-llvm-cov#213]
As title said, I am seeing a lot compilation processes when running `cargo llvm-cov nextest --jobs 1`

**Comment by taiki-e** [comment]
I guess this is a problem in nextest as we are just propagating the --jobs option to nextest.

**Comment by jiangying000** [comment]
`cargo nextest run --build-jobs 10` works

---

but `cargo llvm-cov nextest run --build-jobs 10` fails with:

    error: error: Found argument '--build-jobs' which wasn't expected, or isn't valid in this context    
            If you tried to supply `--build-jobs` as a value rather than a flag, use `-- --build-jobs`
    
    USAGE:
        cargo llvm-cov run [OPTIONS] [-- <ARGS>...]

---

while running `cargo llvm-cov nextest run -- --build-jobs 10` , `--build-jobs` params does not take effect

**Comment by taiki-e** [comment]
> `cargo nextest run --build-jobs 10` works

I'm confused about this -- this seems to be different than the options you originally reported in this issue.

- You originally reported about the case of reducing to one build job not working.
- You originally reported about the case of using `--jobs` option. (cargo-llvm-cov doesn't convert `--jobs` option to `--build-jobs`.)

> but `cargo llvm-cov nextest run --build-jobs 10` fails with:

This is https://github.com/taiki-e/cargo-llvm-cov/issues/151, and will be fixed by https://github.com/taiki-e/cargo-llvm-cov/pull/197

**Comment by jiangying000** [comment]
> > `cargo nextest run --build-jobs 10` works
> 
> I'm confused about this -- this seems to be different than the options you originally reported in this issue.
> 
> - You originally reported about the case of reducing to one build job not working as you expected.
> - You originally reported about the case of using `--jobs` option. (cargo-llvm-cov doesn't convert `--jobs` option to `--build-jobs`.)
> 
> > but `cargo llvm-cov nextest run --build-jobs 10` fails with:
> 
> This is https://github.com/taiki-e/cargo-llvm-cov/issues/151, and will be fixed by https://github.com/taiki-e/cargo-llvm-cov/pull/197
> 

sorry, I should change all the 10's to 1's, the result should be same

**Comment by taiki-e** [comment]
Fixed in #197.

**Comment by jiangying000** [comment]
I can confirm that this issue is resolved
