### ISSUE TITLE
Is it impossible to use nextest profiles?

### ISSUE THREAD

**Issue by kjetilkjeka** [taiki-e/cargo-llvm-cov#216]
I have seen the other issues and comments in #144 related to argument parsing for nextest. I also realize it is a good chance this was already fixed yesterday in #197 and haven't tested to build cargo-llvm-cov from git. I will still report the problem and let you close it if it is already fixed.

No matter how the `--profile ci` flag is specified to `cargo llvm-cov nextest` it seems to use the default nextest profile. 

My use case is to create a test report and a coverage report from the same run to go lighter on compute resources in CI.

**Comment by taiki-e** [comment]
On the current main branch, `--profile ci` still does not work, but that `-P ci` works (since https://github.com/taiki-e/cargo-llvm-cov/pull/197).

And, as for `--profile ci`, it will be fixed by #217.

**Comment by taiki-e** [comment]
The fix has been published in [0.5.0](https://github.com/taiki-e/cargo-llvm-cov/releases/tag/v0.5.0)
