### ISSUE TITLE
Disable coverage for derived traits

### ISSUE THREAD

**Issue by zbraniecki** [taiki-e/cargo-llvm-cov#222]
In a library I work on, we add Derive traits on public structs so that our clients can use them, we fairly often don't need them in our internal work, and we don't want to keep adding tests just to verify that default trait works.

The result is that a lot of our coverage for code like this:

```rust
#[derive(Debug, PartialEq, Eq, Clone, Hash, PartialOrd, Ord, Copy)]
#[non_exhaustive]
pub enum ExtensionType {
    /// Transform Extension Type marked as `t`.
    Transform,
    /// Unicode Extension Type marked as `u`.
    Unicode,
    /// Private Extension Type marked as `x`.
    Private,
    /// All other extension types.
    Other(u8),
}
```

gets flagged with:

> Unexecuted instantiation: <icu_locid::extensions::ExtensionType as core::fmt::Debug>::fmt
> Unexecuted instantiation: <icu_locid::extensions::ExtensionType as core::fmt::Debug>::fmt
> Unexecuted instantiation: <icu_locid::extensions::ExtensionType as core::cmp::PartialEq>::eq
> Unexecuted instantiation: <icu_locid::extensions::ExtensionType as core::cmp::PartialEq>::eq
> Unexecuted instantiation: <icu_locid::extensions::ExtensionType as core::clone::Clone>::clone
> Unexecuted instantiation: <icu_locid::extensions::ExtensionType as core::clone::Clone>::clone
> Unexecuted instantiation: <icu_locid::extensions::ExtensionType as core::hash::Hash>::hash::<_>
> Unexecuted instantiation: <icu_locid::extensions::ExtensionType as core::hash::Hash>::hash::<_>
> Unexecuted instantiation: <icu_locid::extensions::ExtensionType as core::cmp::PartialOrd>::partial_cmp
> Unexecuted instantiation: <icu_locid::extensions::ExtensionType as core::cmp::PartialOrd>::partial_cmp
> Unexecuted instantiation: <icu_locid::extensions::ExtensionType as core::cmp::Ord>::cmp
> Unexecuted instantiation: <icu_locid::extensions::ExtensionType as core::cmp::Ord>::cmp

which makes the coverage noisy and less useful to notice actual coverage gaps.

How can we disable coverage for default derived traits?

**Comment by taiki-e** [comment]
This is the upstream issue: see https://github.com/rust-lang/rust/issues/84605#issuecomment-984287186 and subsequent 3 comments.

**Comment by taiki-e** [comment]
This will be fixed in https://github.com/rust-lang/rust/pull/120185.
