### ISSUE TITLE
Generate multiple output formats without re-running tests

### ISSUE THREAD

**Issue by seanpianka** [taiki-e/cargo-llvm-cov#227]
Hello, thanks for this awesome project!

Is it possible to generate an HTML report, JUnit XML output, and a cobertura report all from a single invocation of the testcases? My test suite takes over 5 minutes to run in some instances, so re-running them for each output format seems wasteful.

**Comment by taiki-e** [comment]
Duplicate of #60. You can do this by calling `cargo llvm-cov report` subcommand (multi times). In the future, I'm considering supporting it as a single option, as mentioned in #60.
