### ISSUE TITLE
`cargo llvm-cov nextest run` skips tests

### ISSUE THREAD

**Issue by aaronenberg** [taiki-e/cargo-llvm-cov#233]
cargo-llvm-cov v0.5.3

Maybe I'm misunderstanding, but the tests are not skipped when running either `cargo llvm-cov` or `cargo nextest run` alone, so my expectations are the tests should not be skipped in this scenario.

Steps to reproduce:

```sh
cargo new foo
cd foo
echo '
#[cfg(test)]
mod test {
    #[test]
    fn test_foo() {
        assert_eq!(1 + 1, 2);
    }
}' >> src/main.rs
cargo llvm-cov nextest run
```

**Comment by taiki-e** [comment]
`cargo llvm-cov nextest` internally calls `cargo nextest run`, so, `run` in `cargo llvm-cov nextest run` is treated as a filter to the test.
https://github.com/taiki-e/cargo-llvm-cov/blob/7e531da0c6ae171eb018ee77155daf6bc7484674/src/main.rs#L335

The help message indicates that the `cargo nextest run`'s options are acceptable, but we probably should be able to make the help message clearer.

https://github.com/taiki-e/cargo-llvm-cov/blob/7e531da0c6ae171eb018ee77155daf6bc7484674/docs/cargo-llvm-cov-nextest.txt#L9

**Comment by aaronenberg** [comment]
Ah, yeah that makes sense. Thanks for being so responsive. Feel free to close.

Would you consider updating the subcommands help displayed by `cargo llvm-cov --help`
```
SUBCOMMANDS:
...
    nextest
                Run tests with cargo nextest
                This internally calls `cargo nextest run`
```
Thoughts?

**Comment by taiki-e** [comment]
> Would you consider updating the subcommands help displayed by `cargo llvm-cov --help`

Sounds good to me.
