### ISSUE TITLE
readme: 'cargo llvm-cov' does not run doc-tests

### ISSUE THREAD

**Issue by santhosh-tekuri** [taiki-e/cargo-llvm-cov#244]
readme suggests to use `cargo llvm-cov` instead of `cargo test`

but there is one difference `cargo llvm-cov` does not run doc-tests.
I think this should be mentioned explicitly in readme.

BTW, I replaced `cargo test` with `cargo llvm-cov` in my CI, and wondering why it is not showing any errors in doc tests.

**Comment by taiki-e** [comment]
readme says:

> Support for doc tests. (this is currently optional and requires nightly, see https://github.com/taiki-e/cargo-llvm-cov/issues/2 for more)

**Comment by santhosh-tekuri** [comment]
I saw it. But as a first time user, I jumped directly to `Usage` section. I guess most first time users to the same and don't realise this .
