### ISSUE TITLE
docs: VS Code integration

### ISSUE THREAD

**Issue by taiki-e** [taiki-e/cargo-llvm-cov#245]
vscode itself and r-a do not have an API for this, but it appears that using the [coverage-gutters](https://marketplace.visualstudio.com/items?itemName=ryanluker.vscode-coverage-gutters) extension can make this work.
https://github.com/rust-lang/rust-analyzer/issues/8881#issuecomment-995188572

If the above way still works well, having an example/guide on this would make sense.

**Comment by Th3Whit3Wolf** [comment]
I currently do this using `llvm-cov nextest --lcov --output-path coverage/lcov.info`. Coverage gutters will automatically detect it. Obviously nextest isn't requried and `/coverage` should be added to `.gitignore`.
