### ISSUE TITLE
[QA] how implement failed if Line Coverage less than 90%?

### ISSUE THREAD

**Issue by ChuanDou2021** [taiki-e/cargo-llvm-cov#246]
I want to implement function that if Line Coverage less than 90%, ci build failed?
Any advice to implement the function ? thanks

**Comment by taiki-e** [comment]
I believe this is already implemented as --fail-under-lines (https://github.com/taiki-e/cargo-llvm-cov/pull/139).

```
        --fail-under-lines <MIN>
            Exit with a status of 1 if the total line coverage is less than MIN percent
```
