### ISSUE TITLE
Docs build is broken

### ISSUE THREAD

**Issue by jotare** [taiki-e/cargo-llvm-cov#248]
Hi, I realized docs are not being built since the last month.

You can follow the build failure here: https://docs.rs/crate/cargo-llvm-cov/0.5.11/builds/754868

You can also reproduce the error generating the docs directly with `cargo doc`.

**Comment by taiki-e** [comment]
docs.rs is for the public API documentation of the library, and there is no public API in the library part of this crate.

https://github.com/taiki-e/cargo-llvm-cov/blob/ad889ca4b1f832f9c2570009eebf44b0fa48c4e8/src/lib.rs#L5-L6

It may be their bug that the `cargo` doc fails with the `#![doc(hidden)]` library, but even if it did work, the docs.rs documentation for the cargo-llvm-cov would be empty.

Considering that crates-io generates links to docs.rs if it is accessible, the current behavior may be rather preferable.
