### ISSUE TITLE
--test-threads override doesn't work

### ISSUE THREAD

**Issue by def-** [taiki-e/cargo-llvm-cov#261]
The README states:

> All the tests are run with RUST_TEST_THREADS=1 to work around [https://github.com/rust-lang/rust/issues/91092]. You can pass --test-threads (e.g., --test-threads=$(nproc)) to override this behavior. (As for nextest, we also set NEXTEST_TEST_THREADS=1.)

But in `nextest` `--test-threads` seems to be ignored when `NEXTEST_TEST_THREADS=1` is set. Could cargo-llvm-cov detect `--test-threads` being set and not set `NEXTEST_TEST_THREADS=1` then?

**Comment by taiki-e** [comment]
Please tell us what the full command you used is.

**Comment by def-** [comment]
This appears to be a problem on my side, sorry.

**Comment by taiki-e** [comment]
FYI, since cargo-llvm-cov [0.5.20](https://github.com/taiki-e/cargo-llvm-cov/releases/tag/v0.5.20), we no longer set RUST_TEST_THREADS/NEXTEST_TEST_THREADS and now adopt a more efficient alternative to workaround rustc bug.
