### ISSUE TITLE
No coverage report after panic in nextest

### ISSUE THREAD

**Issue by def-** [taiki-e/cargo-llvm-cov#262]
Is it expected to get no coverage report after a panic inside a test? My command is `cargo llvm-cov nextest --workspace --lcov --output-path cargotest.lcov --no-fail-fast` in https://github.com/MaterializeInc/materialize/

**Comment by taiki-e** [comment]
Could you try `--ignore-run-fail` flag?

```
    --ignore-run-fail
            Run all tests regardless of failure and generate report

            If tests failed but report generation succeeded, exit with a status of 0.
```

**Comment by def-** [comment]
Tried it and get this error: `error: --ignore-run-fail is not supported for nextest`

**Comment by taiki-e** [comment]
`cargo llvm-cov nextest` now supports `--ignore-run-fail` (v0.5.18, #263).
