### ISSUE TITLE
#[coverage_helper::test] is not working with #[tokio::test]

### ISSUE THREAD

**Issue by Hamzaslipax** [taiki-e/cargo-llvm-cov#273]
Hey there, I have the problem that my tests are also getting tested. So my test coverage is never gonna reach 100%.

How can I ignore the tests getting tested?

Note:
I use `cargo llvm-cov nextest --open`
the coverage_helper doesnt seem to work for me

**Comment by taiki-e** [comment]
dup of #254. no_coverage require nightly as documented.

**Comment by taiki-e** [comment]
Closing in favor of https://github.com/taiki-e/coverage-helper/issues/2
