### ISSUE TITLE
html output break utf-8

### ISSUE THREAD

**Issue by Dushistov** [taiki-e/cargo-llvm-cov#275]
I have lines like this in my codebase:

```rust
 if !matches!(it.next(), Some('A'..='Z') | Some('А'..='Я')) {
        return false;
 }
```

Generating html with such command `cargo llvm-cov --html test`.

For letter 'Я' resulted html code looks like this:
 
```
=&apos;\320<span class='tooltip-content'>5</span></div>\257&apos;
```

so html generator breaks valid utf-8 sequence for 'Я' (`\320\257`) into two parts and insert html code between,
making it invalid.

**Comment by Zalathar** [comment]
This should now be fixed upstream in nightly as of <https://github.com/rust-lang/rust/pull/119033>.

**Comment by taiki-e** [comment]
@Zalathar Great! Thanks for fixing this!
