### ISSUE TITLE
Coverage of specific crate inside a workspace

### ISSUE THREAD

**Issue by tomasro27** [taiki-e/cargo-llvm-cov#278]
Is it possible to specify a specific crate, or folder of files to get coverage?
When I run cargo llvm-cov inside a crate folder, I can see how the tests that run are only the ones on that crate, however, the coverage report includes all files from root folder of workspace as well.
I have been using --ignore-filename-regex flag but is there a way to just specify which files/folder instead of having to exclude all the other files/folders?

Thanks

**Comment by taiki-e** [comment]
I think you can use --package or --exclude option.

**Comment by taiki-e** [comment]
Closing as I think I answered your question.

**Comment by lasantosr** [comment]
@taiki-e Even if you use the --package option with a single package, the report still displays files that the package uses from other members of the workspace.

If a workspace have a package-A and a package-B that has a dependency on package-A, the report for the package-B still shows files from package-A.
