### ISSUE TITLE
Missing lines on async functions with tracing::instrument macro

### ISSUE THREAD

**Issue by dnaka91** [taiki-e/cargo-llvm-cov#282]
I noticed that some of my functions are missing line information when they're processed with the `tracing::instrument` macro. When I look at the HTML report, the source code is there of course, but most of the lines are neither detected as covered nor uncovered.

As soon as I remove the macro, they're detected properly again. I understand macros are always tricky to handle, and I wonder whether this is something that's better reported on the tracing repo's issue tracker?

For now, I can work around it as follows:

```rust
#[cfg_attr(not(coverage), instrument(skip_all, level = "trace"))]
async fn something() {}
```

**Comment by dnaka91** [comment]
Thank you for the quick reply.

Tried playing with a few flags to `rust-cov` but none of them had an effect. But well, I'm not really sure what I'm doing there, as I don't know much about the llvm-cov tools.

I'll follow the bug report for any progress on this. Should I close this issue or leave it open?

**Comment by taiki-e** [comment]
I also confirmed that `-show-expansions=false` doesn't fix this. 

Closing in favor of upstream bug report for now.
