### ISSUE TITLE
#[no_coverage] didn't exclude internal functions and closures inside a function

### ISSUE THREAD

**Issue by mhfan** [taiki-e/cargo-llvm-cov#291]
Thus, require "#[cfg_attr(coverage_nightly, no_coverage)]" prepend before each internal functions/closures for exclusion, e.g.: 

https://github.com/mhfan/inrust/blob/d4bd798028b9d06709b1c65ef92993af805ba4a4/src/calc24.rs#L737C1-L762C6

**Comment by taiki-e** [comment]
This seems like a rustc bug.

Would you mind submitting an issue at https://github.com/rust-lang/rust?

**Comment by taiki-e** [comment]
Thanks. Closing in favor of upstream bug report.
