### ISSUE TITLE
Path dependencies that included in the workspace are displayed in the report, even if --all flag is not used

### ISSUE THREAD

**Issue by taiki-e** [taiki-e/cargo-llvm-cov#31]
This behavior is correct for virtual workspaces, but otherwise it doesn't match the behavior of cargo.

See:
- https://app.codecov.io/gh/time-rs/time
- https://github.com/time-rs/time/blob/4e59ade6c9617ae0d2b73c9d5241e9e9f609218b/.github/workflows/build.yaml#L391

**Comment by jhpratt** [comment]
For what it's worth, I find it quite nice to have the workspace included. Admittedly this likely wouldn't be the case for non-workspace dependencies.

**Comment by taiki-e** [comment]
The problem is that even if `--all`/`--workspace` flag is not being used, other crates will be displayed in the report.

If you want to get the coverage of other crates in the workspace (and the workspace is not virtual), you have to use the `--all` or `--workspace` flag (like `cargo test`). Otherwise, the tests will not be run on those crates, so the reported coverage will be lower than it actually is.

**Comment by jhpratt** [comment]
Ah, gotcha. The crate I was happy to see it for was a proc macro, which doesn't have tests of its own. Either way I don't mind typing a couple more characters.
