### ISSUE TITLE
Line Coverage and Number of Lines in the HTML report are different from grcov

### ISSUE THREAD

**Issue by qveera** [taiki-e/cargo-llvm-cov#315]
How it calculates the number of the lines? When I compare it with grcov reports, grcov is providing proper reports compared to cargo-llvm-cov.

**Comment by taiki-e** [comment]
Please provide a detailed description and reproduction of the problem.

---

FYI, I have previously received questions from others regarding the differences between grcov and cargo-llvm-cov coverage results, and the following is the explanation [I provided at that time](https://github.com/nextest-rs/nextest/issues/652#issuecomment-1328257148).

> FWIW, as for the difference in coverage results between grcov and cargo-llvm-cov, I think it is related to the fact that grcov seems to count coverage of test files by default, while cargo-llvm-cov tries to avoid this as much as possible.
> 
> The reason for cargo-llvm-cov tries to avoid this as much as possible is that counting the coverage of the test code itself as part of the coverage of the test target (library or binary being tested) would result in a different coverage than the actual coverage of the test target.[^1] (in many cases the test code itself is 100% covered)
> 
> So, it is not surprising that the coverage percentages drop when switching from grcov to cargo-llvm-cov; rather, it is maybe more accurate result of the coverage of the test target.
> 
> [^1]: [The approach adopted by cargo-llvm-cov is not yet perfect, although](https://github.com/taiki-e/cargo-llvm-cov/issues/123)
