### ISSUE TITLE
Separate build from execution & report generation

### ISSUE THREAD

**Issue by MiniaczQ** [taiki-e/cargo-llvm-cov#319]
This is a mirror issue to another coverage tool https://github.com/xd009642/tarpaulin/issues/1352

Is it possible to build binaries, then move them to special environments (like docker images) and run coverage and reports there separately?

**Comment by taiki-e** [comment]
I don't know your exact use case, but `show-env` + `report` might work: https://github.com/taiki-e/cargo-llvm-cov?tab=readme-ov-file#get-coverage-of-external-tests

**Comment by MiniaczQ** [comment]
The exact use case would be building all of the test binaries together, with cache available, then separating them to:
- unit tests, no special environment
- integration tests, docker image, docker compose with specific services available
then combining all results through another tool

**Comment by taiki-e** [comment]
If you want to run the built binaries in containors you need to bind the target directory and map LLVM_PROFILE_FILE env var properly, but show-env should work.

**Comment by MiniaczQ** [comment]
Alright, I'll try it out and see how it goes.
Thank you :)

**Comment by taiki-e** [comment]
> If you want to run the built binaries in containors you need to bind the target directory and map LLVM_PROFILE_FILE env var properly

I checked locally and something like the following worked:

```sh
source <(cargo llvm-cov show-env --export-prefix)

cargo build

docker run --rm -d -it \
  -v "$(pwd)":/workdir \
  --env LLVM_PROFILE_FILE="${LLVM_PROFILE_FILE/"$(pwd)"//workdir}" \
  ubuntu sh -c '/workdir/target/debug/<bin-name> --version'

cargo llvm-cov report --html
```

**Comment by MiniaczQ** [comment]
The assumption is that I provide all the test binaries paths, which requires build result parsing the build results.
I believe this is also different between `cargo test` and `nextest`

**Comment by MiniaczQ** [comment]
I did a setup with nextest, since it provides a better way to package test binaries, here's the attempt
https://github.com/nextest-rs/nextest/issues/1036

**Comment by taiki-e** [comment]
Closing -- this seems to be solved https://github.com/nextest-rs/nextest/issues/1036#issuecomment-1761676089
