### ISSUE TITLE
Ignore function signatures in code coverage report, while not ignore function bodies?

### ISSUE THREAD

**Issue by fzyzcjy** [taiki-e/cargo-llvm-cov#328]
Given https://github.com/taiki-e/cargo-llvm-cov/issues/327, one work around may be, if we can somehow ignore the function *signatures*, while keeping the function bodies un-ignored. However, I am not sure whether this is possible currently.

For implementation, one naive way may be:
* Users add comments such as `// coverage_off_begin` and `// coverage_off_end` (like in other langauges)
* Adding a post-processing script, which inputs LCOV report (or whatever), parse the source code, sees (e.g.) line 10-15 is marked ignored by that comment, then change LCOV report by removing those lines.

**Comment by taiki-e** [comment]
I prefer to fix the bug itself rather than add an odd workaround to avoid the odd bug.

**Comment by fzyzcjy** [comment]
Totally agree!

Btw I already add workarounds in https://github.com/fzyzcjy/flutter_rust_bridge ...
