### ISSUE TITLE
Demangling

### ISSUE THREAD

**Issue by smoelius** [taiki-e/cargo-llvm-cov#341]
I happened upon this recently: https://github.com/taiki-e/cargo-llvm-cov/blob/071a9efe6b9837a1e0ddc522df98e0ab7170e488/src/cli.rs#L962

Is it possible for mere mortals to use that subcommand (even if its unstable)?

If it's not possible, is there another demangling approach that you recommend?

(This is relate to #325. The symbols in those results are mangled, which is unfortunate.)

**Comment by taiki-e** [comment]
> is there another demangling approach that you recommend?



See https://github.com/luser/rustfilt

**Comment by smoelius** [comment]
Oh wow. It looks like it's as simple as running `rustfilt -i old-lcov-file -o new-lcov-file`. This also seems to solve my [crate disambiguators issue](https://github.com/taiki-e/cargo-llvm-cov/issues/325).

Just to confirm, this is the approach you had in mind?

Not something more sophisticated like using `-X` flags (as suggested [here](https://doc.rust-lang.org/rustc/instrument-coverage.html))?

**Comment by taiki-e** [comment]
> This also seems to solve my [crate disambiguators issue](https://github.com/taiki-e/cargo-llvm-cov/issues/325).

Oh, I didn't know that using rustfilt would fix #325. I guess that means the logic used there is better than [what we are using](https://github.com/taiki-e/cargo-llvm-cov/blob/071a9efe6b9837a1e0ddc522df98e0ab7170e488/src/demangle.rs). We should fix our implementation with reference to it.

**Comment by smoelius** [comment]
Thanks!
