### ISSUE TITLE
Code compiled with different #[cfg] flags shows up as different instantiations

### ISSUE THREAD

**Issue by Ekleog-NEAR** [taiki-e/cargo-llvm-cov#344]
Initially reported by @Dushistov [here](https://github.com/taiki-e/cargo-llvm-cov/issues/276#issuecomment-1544687182):

Oh, that's why not generic functions some times have several instantiation according to html generated by cargo-llvm-cov:

![237814209-98e1616c-04a5-4da8-b509-b079f137ff40](https://github.com/taiki-e/cargo-llvm-cov/assets/96595974/192ce4c3-1eab-4dda-b86c-c750961d0e6c)

The solution might end up being the same as #43

**Comment by michaelvlach** [comment]
As taiki-e said in the other thread this is a problem of LLVM and not much can be done in cargo-llvm-cov about it. The coverage profiles should be merged but llvm-cov/llvm-profdata/llvm-report would need to do that.

**Comment by michaelvlach** [comment]
> (I'm wondering if this may be another instance of #325.)

It almost certainly is. I am also pleasantly surprised that I was wrong and that the issue can be solved with a demangler even with current LLVM implementation! That is great news and could improve teh quality of the coverage reporting.

**Comment by taiki-e** [comment]
This probably has been fixed in v0.6.7 (https://github.com/taiki-e/cargo-llvm-cov/pull/354). Could you recheck this with v0.6.7?

**Comment by michaelvlach** [comment]
> This probably has been fixed in v0.6.7 (#354). Could you recheck this with v0.6.7?

Thanks for this, I have tried it and I see no missing lines with multiple instantiations anymore as long as the coverage overlaps.

The only remaining issue is `await` not always mark as executed even though call cahing before/after was executed. But that is a different issue I think not related to demangler or instantiations.

**Comment by taiki-e** [comment]
Thanks for confirming!

> The only remaining issue is `await` not always mark as executed even though call cahing before/after was executed. But that is a different issue I think not related to demangler or instantiations.

Yeah, it's different rustc bug: https://github.com/rust-lang/rust/issues/98712
