### ISSUE TITLE
Coverage of build.rs

### ISSUE THREAD

**Issue by jayvdb** [taiki-e/cargo-llvm-cov#374]
We have a code generator project invoked from a bunch of other project build.rs scripts, which are definitely getting invoked when the tests are run, but the code generator has 0% test coverage.

I assume this is because cargo-llvm-cov cant get into the build process of build.rs , and probably there is a bug upstream in the rust project about this.

**Comment by taiki-e** [comment]
Could you provide a reproduction?

As I said in several issues, it is always difficult to investigate an issue unless I can reproduce it on my end.

See also help messages:

```
--include-build-script
            Include build script in coverage report
```

```
--target <TRIPLE>
            Build for the target triple

            When this option is used, coverage for proc-macro and build script will not be displayed
            because cargo does not pass RUSTFLAGS to them.
```

**Comment by jayvdb** [comment]
Sorry I was not aware of `--include-build-script` .  That did the trick.  Sorry for the noise.
