### ISSUE TITLE
`unreachable` coverage

### ISSUE THREAD

**Issue by wyfo** [taiki-e/cargo-llvm-cov#378]
As the name suggests `unreachable` (and `hint::unreachable_unchecked`) should never be reached. Does it make sense to automatically exclude unreachable branches from coverage? Is it even possible?

**Comment by taiki-e** [comment]
There is an open upstream PR to implement this: https://github.com/rust-lang/rust/pull/120013
See also https://github.com/rust-lang/rust/issues/80549

**Comment by wyfo** [comment]
My bad, I should have looked there first.
I imagine that you prefer having the problem solved on Rust side rather than hacking `llvm-cov` result, so I will close the issue.
