### ISSUE TITLE
Does not work with async closure

### ISSUE THREAD

**Issue by vnghia** [taiki-e/cargo-llvm-cov#389]
Basically title, I put a very simple reproduction [here](https://github.com/vnghia/llvm-cov-async-closure). You can see the CI log as well. I know this feature is unstable so I just want to ask if I need to setup something (like LLVM version for example) to get it working.

Thank you very much for this tool!

**Comment by taiki-e** [comment]
This is a rustc bug: https://github.com/rust-lang/rust/issues/131190
