### ISSUE TITLE
can get coverage of C/C++ code, how can i mock for c

### ISSUE THREAD

**Issue by zaq7434** [taiki-e/cargo-llvm-cov#390]
I don't want to write a separate test framework for the C code in the project. Cargo-llvm-cov can generate code coverage for C, and I'm glad it has this feature. 

However, now I have encountered a problem: how do I mock C code? Could you give me some suggestions? 

Thanks.

**Comment by taiki-e** [comment]
Sorry I'm not sure what you mean, but are you saying that you want to exclude C/C++ code from the coverage results?
