### ISSUE TITLE
show-env inconsistent output after --export-prefix

### ISSUE THREAD

**Issue by asvrada** [taiki-e/cargo-llvm-cov#396]
**What's the issue**
In PowerShell, below call would produce inconsistent key/value pairs

```
> cargo llvm-cov show-env
CARGO_ENCODED_RUSTFLAGS="-Ccontrol-flow-guard▼-Ctarget-feature=+crt-static▼-Clink-args=/DYNAMICBASE /CETCOMPAT /force:guardehcont▼-Cehcont_guard▼-C▼instrument-coverage▼--cfg=coverage▼--cfg=trybuild_no_target"

> cargo llvm-cov show-env --export-prefix
export RUSTFLAGS="\"-Ccontrol-flow-guard -Ctarget-feature -C instrument-coverage --cfg=coverage --cfg=trybuild_no_target"

> cargo llvm-cov show-env
RUSTFLAGS="\"-Ccontrol-flow-guard -Ctarget-feature -C instrument-coverage --cfg=coverage --cfg=trybuild_no_target"
```

Notice the third call no longer returns the same as the first one, even though the command is the same.

**Comment by taiki-e** [comment]
Were any operations performed between these command invocations?

Also, can this be reproduced if only these commands were invoked on a PowerShell that was started in a clean state?

**Comment by asvrada** [comment]
> Were any operations performed between these command invocations?
> 
> Also, can this be reproduced if only these commands were invoked on a PowerShell that was started in a clean state?

No other commands, clean powershell session

**Comment by asvrada** [comment]
I looked into the code base and thought this is a rare case.

The project I am working on adds `-Clink-args=/DYNAMICBASE /CETCOMPAT`, since it contains whitespace, it cannot be properly read by `RUSTFLAGS`, so its encoded into `CARGO_ENCODED_RUSTFLAGS`
