### ISSUE TITLE
Exclude instantiations from statistics?

### ISSUE THREAD

**Issue by jaskij** [taiki-e/cargo-llvm-cov#397]
A few of the structs in my code `#[derive(valuable::Valuable)]` from [`valuable`](https://docs.rs/valuable/latest/valuable/). Those derives show up on the report as not-covered, which is fine, but I would like to exclude them from the statistics. Or the whole report, either way is fine.

Is this something that is achievable and I'm just missing it, or is not currently supported?

**Comment by taiki-e** [comment]
With the current Rust coverage mechanism, this needs to be handled on the derive macro side.

Perhaps we need to stabilize the `#[coverage(off)]` attribute first.

See also https://github.com/rust-lang/rust/issues/84605#issuecomment-984287186 and subsequent 3 comments.

**Comment by taiki-e** [comment]
Considering https://github.com/rust-lang/rust/pull/120185, I think using #[automatically_derived] in valueable-derive resolves this issue.

Filed https://github.com/tokio-rs/valuable/pull/136 to to it.
