### ISSUE TITLE
"truncated coverage data" error since nightly-2024-11-29

### ISSUE THREAD

**Issue by inflation** [taiki-e/cargo-llvm-cov#400]
```
error: failed to load coverage: 'target/llvm-cov-target/debug/deps/jpegxl_rs-e7526f175a583cb9': truncated coverage data
error: could not load coverage information
```

https://github.com/inflation/jpegxl-rs/actions/runs/12043279943/job/33682626134

CI failed on another PR so I rerun the previously succeeded action and found out it failed too.

**Comment by taiki-e** [comment]
This is rustc bug: https://github.com/rust-lang/rust/issues/133606

**Comment by Zalathar** [comment]
Reverted upstream by https://github.com/rust-lang/rust/pull/133608; should be fixed in the next nightly.

**Comment by taiki-e** [comment]
Fixed in nightly-2024-11-30.
