### ISSUE TITLE
install instructions fail with error message

### ISSUE THREAD

**Issue by alexanderkjall** [taiki-e/cargo-llvm-cov#406]
The install instructions here: https://github.com/taiki-e/cargo-llvm-cov/blob/main/README.md?plain=1#L623

produce this result on my arch linux machine:

```
[capitol@batia debcargo]$ cargo +stable install cargo-llvm-cov
error: no such command: `+stable`

	Cargo does not handle `+toolchain` directives.
	Did you mean to invoke `cargo` through `rustup` instead?
[capitol@batia debcargo]$ cargo --version
cargo 1.83.0 (5ffbef321 2024-10-29)
```

**Comment by taiki-e** [comment]
Please drop `+stable` for non-rustup environment. The current readme assumes the use of rustup, which is the popular way to install Rust.

Also, you seem to be installing Rust from the package manager, why not also install cargo-llvm-cov from the package manager?
https://github.com/taiki-e/cargo-llvm-cov/blob/main/README.md#via-pacman-arch-linux
