### ISSUE TITLE
Failed to load coverage: The file was not recognized as a valid object file

### ISSUE THREAD

**Issue by davidhewitt** [taiki-e/cargo-llvm-cov#48]
Thanks for creating this project; it looks like a really nice way to abstract over `-Z instrument-coverage`!

I was just testing this out on CI for PyO3 and it seems like some unintended files are being picked up by the tool when building for the PyO3 workspace. See https://github.com/PyO3/pyo3/runs/3271084242?check_suite_focus=true

**Comment by jhpratt** [comment]
Try `cargo clean`. I just did and it worked :+1:
