### ISSUE TITLE
LLVM Profile Warning: Unable to merge profile data: source profile file is not compatible.

### ISSUE THREAD

**Issue by jhpratt** [taiki-e/cargo-llvm-cov#51]
https://github.com/time-rs/time/runs/3271156683?check_suite_focus=true#step:6:717

```text
LLVM Profile Warning: Unable to merge profile data: source profile file is not compatible.
LLVM Profile Error: Profile Merging of file $DIR/target/llvm-cov-target/time-13776624154103039134_0.profraw failed: File exists
LLVM Profile Error: Failed to write file "$DIR/target/llvm-cov-target/time-13776624154103039134_0.profraw": File exists
```

This is without a cache hit (I'm using a new key), so this isn't an incremental issue. I'm not able to reproduce this locally (Fedora 34, 64 bit).

**Comment by taiki-e** [comment]
1. locally (macOS, with both rust nightly-2021-08-07 and nightly-2021-08-08), I cannot reproduce this.
2. On GitHub actions (ubuntu-20.04, with rust nightly-2021-08-07), I *can* reproduce this on a fork of time-rs/time. (https://github.com/taiki-e/time/runs/3272592463?check_suite_focus=true)
3. On GitHub actions (ubuntu-20.04, with rust nightly-2021-08-08), I cannot reproduce this on a fork of time-rs/time. (https://github.com/taiki-e/time/runs/3272458275?check_suite_focus=true)

So, I guess this is a bug (or odd interaction with GitHub actions) in rust nightly-2021-08-07.

**Comment by jhpratt** [comment]
I guess I'll wait a day and see what happens 🤷🏽

**Comment by jhpratt** [comment]
Just reran the tests without changing a thing. Coverage succeeded. The only failure is unrelated to this; closing as such.
