### ISSUE TITLE
Add support for printing out a summary

### ISSUE THREAD

**Issue by Cogitri** [taiki-e/cargo-llvm-cov#77]
Hello,

I'm currently using cargo-llvm-cov on Gitlab CI. Gitlab CI has a neat feature where it can display the coverage percentage right next to a change if it can parse it from the CI log via Regex. As such it'd be nice if there was a command similar to `llvm-cov report` which just prints a quick overview of the per-file coverage and the total coverage.

**Comment by taiki-e** [comment]
- The default summary output is the output of `llvm-cov report`, so I guess it probably works. (I have little experience with GitLab, and I haven't actually tested it)

  ```console
  cargo llvm-cov
  ```

  Or you may need to redirect it to stderr (`>&2`).

- If `llvm-cov report` does not work, `lcov --list` is likely to work.

  ```console
  apt-get install lcov
  cargo llvm-cov --lcov --output-path lcov.info
  lcov --list lcov.info
  ```

  refs: https://stackoverflow.com/questions/50276744/gitlab-ci-yml-cpp-coverage-report

**Comment by Cogitri** [comment]
Oh I didn’t realise I can run cargo llvm-cov without an argument like —html or —text. running it like this is exactly what I needed, thanks!
