### ISSUE TITLE
Why is the target directory cleared when CI is set?

### ISSUE THREAD

**Issue by fourbytes** [taiki-e/cargo-llvm-cov#78]
I've just moved our projects from Tarpaulin to cargo-llvm-cov and coverage is much more accurate. I noticed however that our caching stopped working and it took me a good while to figure out why, but it seems to be due to [this line](https://github.com/taiki-e/cargo-llvm-cov/blob/3c6ecc72e15b99d0c8ad762f6b0e309299d06b02/src/main.rs#L117) which cleans the target directory when the `CI` environment variable is set.

Is there a particular reason for this? If I manually unset `CI` I am able to get caching working nicely again without recompiling hundreds of dependencies. Imho it would be better to leave it up to the user with an `--always-clean` flag or similar.

**Comment by taiki-e** [comment]
The [current heuristics for build artifacts cleanup](https://github.com/taiki-e/cargo-llvm-cov/blob/3c6ecc72e15b99d0c8ad762f6b0e309299d06b02/src/main.rs#L99-L105) are a bit rough.

- If you do not remove build artifacts of crates to be measured for coverage (i.e., crates in the workspace, or current crate), you may get false positives/false negatives in reports. (Confirmed in several projects. Also, this should not be a problem specific to cargo-llvm-cov.)
- External dependencies'  build artifacts *probably* do not actually need to be removed.

So, the right way here is probably to get the names of the crates to be measured for coverage and remove the build artifacts for those crates using (relatively recently added) `--package` option of `cargo clean`.

**Comment by fourbytes** [comment]
Gotcha, removing artifacts for only crates being measured seems like a great way to go. Thanks.

**Comment by taiki-e** [comment]
Solved in [v0.1.4](https://github.com/taiki-e/cargo-llvm-cov/releases/tag/v0.1.4).
