### ISSUE TITLE
Add `--workspace` flag to `clean` subcommand

### ISSUE THREAD

**Issue by taiki-e** [taiki-e/cargo-llvm-cov#81]
It would be useful to have a flag to remove only artifacts that may affect the coverage results, using the same way as https://github.com/taiki-e/cargo-llvm-cov/pull/79.

```
cargo llvm-cov clean --workspace # remove artifacts that may affect the coverage results
cargo llvm-cov --no-report --features a
cargo llvm-cov --no-report --features b
cargo llvm-cov --no-run --lcov
```

**Comment by taiki-e** [comment]
FYI @davidhewitt: I think it will be possible to cache the target directory again in [pyo3's coverage CI](https://github.com/PyO3/pyo3/blob/b1abe039842d8ec8958d52c1485efd3f96537282/.github/workflows/ci.yml#L216-L217) once this is implemented.

**Comment by davidhewitt** [comment]
👍 sounds great! I'll update pyo3's CI once implemented.

How do you expect this to interact with coverage for proc macros? In some ways it's useful to rebuild the entire pyo3 test suite so that proc macro invocations are covered. Though it would be nice to not need to rebuild all dependencies!

**Comment by taiki-e** [comment]
> How do you expect this to interact with coverage for proc macros? In some ways it's useful to rebuild the entire pyo3 test suite so that proc macro invocations are covered. Though it would be nice to not need to rebuild all dependencies!

The way introduced in #79 will remove trybuild's build artifacts in the same way it did for normal build artifacts.
So I think proc-macro coverage will also work well without any additional action.

https://github.com/taiki-e/cargo-llvm-cov/blob/eb7c3f350bb787d6a91fcbb1ee28af4f55c678ce/src/main.rs#L135-L149

(By the way, in 0.1.0, trybuild's build artifacts were in `target/tests/target`, but in 0.1.1+, they are now generated in `target/llvm-cov-target/tests/target`. (https://github.com/taiki-e/cargo-llvm-cov/commit/bd93d1928eec5c6acb62617c02951dc4f9674508))

**Comment by davidhewitt** [comment]
Brilliant!

**Comment by taiki-e** [comment]
> The way introduced in #79 will remove trybuild's build artifacts in the same way it did for normal build artifacts.

I found that the way introduced in #79 did not remove the trybuild artifacts correctly. #85 also includes a fix for that problem.

**Comment by taiki-e** [comment]
Added in 0.1.5.
