### ISSUE TITLE
`-failure-mode` option?

### ISSUE THREAD

**Issue by smoelius** [taiki-e/cargo-llvm-cov#90]
Would you consider a PR to pass a `-failure-mode` option to `llvm-profdata merge`?
https://llvm.org/docs/CommandGuide/llvm-profdata.html#cmdoption-llvm-profdata-merge-failure-mode

**Comment by taiki-e** [comment]
Seems to make sense to have such an option.

**Comment by smoelius** [comment]
Cool. Thanks. I'll try to submit something soon.

**Comment by smoelius** [comment]
Sorry, I just noticed this:
https://github.com/taiki-e/cargo-llvm-cov/blob/5fce8956d921c84e3119302cdc9e4ee006b4445d/src/env.rs#L14-L16
I can still submit a PR if you like. But since what I want can be achieved through `CARGO_LLVM_PROFDATA_FLAGS`, maybe adding the option isn't necessary?

**Comment by taiki-e** [comment]
I’m fine with either.
The environment variable is to allow us to adjust the behavior of llvm-cov and llvm-profdata without changing the source of cargo-llvm-cov.
However, if the flag is useful, it would make sense to add it to cargo-llvm-cov itself so that users can use it easily.

**Comment by smoelius** [comment]
OK. I'll still submit the PR then.

Question: I was planning to write at least one test to the effect of:
* generate two or more instrumentation profiles
* perturb the header of one
* verify that `cargo-llvm-cov` succeeds with `--failure-mode=all`

Where do you think a test like that should go?

**Comment by taiki-e** [comment]
I usually add tests using the following steps:

1\. add test crate to `tests/fixtures/crates`. (or using existing test crate) [example](https://github.com/taiki-e/cargo-llvm-cov/tree/d9c7c5508ceab36568fcacd86cd41ac1177ed147/tests/fixtures/crates/merge)
2\. add test to `tests/test.rs` that run `target/debug/cargo-llvm-cov` executable. [example](https://github.com/taiki-e/cargo-llvm-cov/blob/d9c7c5508ceab36568fcacd86cd41ac1177ed147/tests/test.rs#L116)
3\. run test. (the resulting coverage will be output to `tests/fixtures/coverage-reports`.)
4\. if check on stderr or stdout, use stdout_contains or stderr_contains. [example](https://github.com/taiki-e/cargo-llvm-cov/blob/d9c7c5508ceab36568fcacd86cd41ac1177ed147/tests/test.rs#L196)

Considering what kind of tests are needed for this feature, something similar to [merge](https://github.com/taiki-e/cargo-llvm-cov/blob/d9c7c5508ceab36568fcacd86cd41ac1177ed147/tests/test.rs#L116) or [clean_ws](https://github.com/taiki-e/cargo-llvm-cov/blob/d9c7c5508ceab36568fcacd86cd41ac1177ed147/tests/test.rs#L144) test will probably be needed.
